#!/usr/bin/env bash
set -Eeu

errors=()

for dir in $(fd --type directory --max-depth=1); do
  if ! [[ -f "$dir/install" ]]; then
    errors+=("$dir does not have an 'install' script entry point")
  elif ! [[ -x "$dir/install" ]]; then
    errors+=("$dir/install is not set executable")
  fi
done

# Does everything look ok?
if [ ${#errors[@]} -eq 0 ]; then
    echo "Everything looks good"
    exit 0
else
    echo "Somethings looks wrong..."
    for error in "${errors[@]}"
    do
     echo "$error"
   done
fi
