---
repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.1.0
    hooks:
      - id: nixpkgs-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: git-check
      - id: markdownlint
      # todo: send up MR to change /bin/bash /usr/bin/env bash
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
