#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mkdir -p "$DIR/.cache"

#check_file() {
#  if ! sha256sum --check --ignore-missing SHA256SUMS; then
#    echo "Checksum failed."
#    return 1
#  fi
#  return 0
#}

download_file() {
    curl --progress-bar --show-error --remote-name "$@"
}

download_if_not_in_cache() {
    pushd "$DIR/.cache"
    if ! [ -f "$1" ]; then
       download_file --output "$1" "$2"
   fi
}


download_if_not_in_cache "ubuntu-19.10.1-arm64.img" "http://cdimage.ubuntu.com/releases/19.10.1/release/ubuntu-19.10.1-preinstalled-server-arm64+raspi3.img.xz"
download_if_not_in_cache "kernel-qemu-4.4.34-jessie" "https://raw.githubusercontent.com/dhruvvyas90/qemu-rpi-kernel/master/kernel-qemu-4.4.34-jessie"

unxz --verbose "$DIR/kernel-qemu-4.4.34-jessie"
