#!/usr/bin/env bash
set -Eeu
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "/tmp/_common.bash"
common.install_packages initramfs-tools linux-headers-generic

echo 'root:root' | chpasswd # todo: pull from password manager
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

# this is what builds the updated initrd to network boot with. It will run the
# scripts in /etc/initramfs-tools.
update-initramfs -cvu
