#!/usr/bin/env bash
set -Eeu

# todo: secure this
#   auth.allow

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

packages=(
  software-properties-common
  xfsprogs
)
apt-get update -qq
apt-get install -qy  "${packages[@]}"


add-apt-repository ppa:gluster/glusterfs-9 -y
packages=(
  glusterfs-client
  glusterfs-server
)
apt-get update -qq
apt-get install -qy  "${packages[@]}"
apt-get clean all


systemctl enable glusterd.service

cp "$DIR/gluster-init.service" /etc/systemd/system/
cp "$DIR/gluster-init.timer"  /etc/systemd/system/
systemctl enable gluster-init.timer

mkdir -p /usr/local/bin/
cp "$DIR/gluster-init.sh" /usr/local/bin/gluster-init.sh
