#!/usr/bin/env bash
set -Eeu

# todo: secure this
#   auth.allow

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "/tmp/_common.bash"
common.install_packages software-properties-common xfsprogs jq

add-apt-repository ppa:gluster/glusterfs-9 -y
common.install_packages glusterfs-client glusterfs-server


systemctl enable glusterd.service

cp "$DIR/gluster-init.service" /etc/systemd/system/
cp "$DIR/gluster-init.timer"  /etc/systemd/system/
systemctl enable gluster-init.timer

mkdir -p /usr/local/bin/
cp "$DIR/gluster-init.sh" /usr/local/bin/gluster-init.sh

cp "$DIR/check_glusterfs_health" /usr/local/bin/check_glusterfs_health
