#!/usr/bin/env bash
set -Eeu
# https://github.com/acassen/keepalived
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "/tmp/_common.bash"
common.install_packages keepalived

mkdir -p /etc/keepalived
cp "$DIR/keepalived.conf" /etc/keepalived/keepalived.conf
cp "$DIR/notify.sh" /etc/keepalived/notify.sh
chmod +x /etc/keepalived/notify.sh
