#!/usr/bin/env bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mkdir -p /etc/keepalived
cp "$DIR/keepalived.conf" /etc/keepalived/keepalived.conf
cp "$DIR/notify.sh" /etc/keepalived/notify.sh
chmod +x /etc/keepalived/notify.sh
