---
# Configure Raspberry Pi
- name: Configure Raspberry Pi
  hosts: all
  remote_user: ansible
  become: yes
  roles:
    - common
    #- dev-sec.ssh-hardening
    #- dev-sec.os-hardening
    - brianshumate.consul
    - brianshumate.nomad
