#!/usr/bin/env bash
set -Eeu

# https://docs.docker.com/engine/install/ubuntu/
apt-get update -qq
apt-get install -qq \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  lsb-release

# todo: add this key as an artifact to this repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -qq
apt-get install -qq docker-ce docker-ce-cli containerd.io
