#!/usr/bin/env bash
set -Eeu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

VERSION=2.4.7

cd "$(mktemp -d)" && {
  curl --silent --show-error --output traefik.tar.gz -L "https://github.com/containous/traefik/releases/download/v${VERSION}/traefik_v${VERSION}_linux_amd64.tar.gz"
  tar -zxf traefik.tar.gz
  mv ./traefik /usr/bin/traefik
  chmod +x /usr/bin/traefik

  useradd -r -s /bin/false -U -M traefik
}

cp "$DIR/traefik.service" /etc/systemd/system/traefik.service

mkdir --parents /etc/traefik
cp "$DIR/traefik.toml" /etc/traefik/traefik.toml
