---
version: "3.7"
services:
  pixiecore:
    build: ./pixiecore
    network_mode: "host"  # need to listen for dhcp on host
    command: [
      "api",
      "http://util.dmz.509ely.com:9090/",
      "--log-timestamps"
    ]

  file-server:
    image: nginx:stable
    volumes:
      - ./files:/usr/share/nginx/html:ro
    ports:
      - 8080:80

  pxe-api:
    build: ./pxe-api
    image: registry-prod.apps.509ely.com/pxe-api:latest
    ports:
      - 9090:5000
    working_dir: /app
