#!/usr/bin/env bash
set -e

# this whole script is just a bandaid. I should fix the source of these issues.
# One of these days... For now its easier to just run this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# this works because I know where the scripts dir lives
ROOT="$(dirname "$DIR")"

sudo chown -R "$(whoami)" "$ROOT/dist"
