#!/usr/bin/env bash
set -eu

VERSION=2.2.1

cd "$(mktemp -d)" && {
  curl --silent --show-error --output traefik.tar.gz -L "https://github.com/containous/traefik/releases/download/v${VERSION}/traefik_v${VERSION}_linux_amd64.tar.gz"
  tar -zxf traefik.tar.gz
  mv ./traefik /usr/bin/traefik
  chmod +x /usr/bin/traefik

  useradd -r -s /bin/false -U -M traefik
}

cat << SYSTEMD > /etc/systemd/system/traefik.service
[Unit]
Description=Traefik
Documentation=https://docs.traefik.io
#After=network-online.target
#AssertFileIsExecutable=/usr/bin/traefik
#AssertPathExists=/etc/traefik/traefik.toml

[Service]
# Run traefik as its own user (create new user with: useradd -r -s /bin/false -U -M traefik)
#User=traefik
#AmbientCapabilities=CAP_NET_BIND_SERVICE

# configure service behavior
Type=notify
ExecStart=/usr/bin/traefik --configFile=/etc/traefik/traefik.toml
Restart=always
WatchdogSec=1s

# lock down system access
# prohibit any operating system and configuration modification
#ProtectSystem=strict
# create separate, new (and empty) /tmp and /var/tmp filesystems
#PrivateTmp=true
# make /home directories inaccessible
#ProtectHome=true
# turns off access to physical devices (/dev/...)
#PrivateDevices=true
# make kernel settings (procfs and sysfs) read-only
#ProtectKernelTunables=true
# make cgroups /sys/fs/cgroup read-only
#ProtectControlGroups=true

# allow writing of acme.json
#ReadWritePaths=/etc/traefik/acme.json
# depending on log and entrypoint configuration, you may need to allow writing to other paths, too

# limit number of processes in this unit
#LimitNPROC=1

[Install]
WantedBy=multi-user.target
SYSTEMD

mkdir --parents /etc/traefik
cat << CONFIG > /etc/traefik/traefik.toml
[api]
  dashboard = true
[providers.consulCatalog]
  exposedByDefault = false
  [providers.consulCatalog.endpoint]
    address = "http://127.0.0.1:8500"
[entryPoints.web]
  address = "10.25.89.5:80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
[entryPoints.websecure]
  address = "10.25.89.5:443"
[certificatesResolvers.myresolver.acme]
  email = "kyle@ondy.org"
  storage = "/mnt/nfs/traefik/acme/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

# https://docs.traefik.io/operations/dashboard/#secure-mode
[http.routers.my-api]
  rule = "Host(\`traefik.apps.509ely.com\`)"
  service = "api@internal"
  middlewares = ["traefik-auth"]

[http.middlewares.traefik-auth.basicAuth]
  users = [
    "kyle:\$apr1\$C.zhFNPC\$uBk/NdASEIjqnNGGu4Sv//",
  ]
CONFIG
