#!/usr/bin/env bash
set -eu
export NOMAD_VERSION="0.11.1"

# todo: abscrt this out
ARCH=$(uname -m)
NOMAD_ARCH=
if [[ $ARCH == "x86_64" ]]; then
  NOMAD_ARCH="amd64"
elif [[ $ARCH == "armv7l" ]]; then
  NOMAD_ARCH=armhfv6
else
  echo "unknown architecture: $ARCH"
  exit 1
fi


# https://www.nomadproject.io/docs/install/production/deployment-guide/
pushd "$(mktemp -d)" && {
  curl --silent --show-error --remote-name https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_${NOMAD_ARCH}.zip
  unzip nomad_${NOMAD_VERSION}_linux_${NOMAD_ARCH}.zip
  chown root:root nomad
  mv nomad /usr/local/bin/
  nomad version
  nomad -autocomplete-install
  complete -C /usr/local/bin/nomad nomad
}

cat << "SYSTEMD" > /etc/systemd/system/nomad.service
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=10

[Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d
KillMode=process
KillSignal=SIGINT
LimitNOFILE=infinity
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
StartLimitBurst=3
TasksMax=infinity

[Install]
WantedBy=multi-user.target
SYSTEMD

sudo mkdir --parents /opt/nomad
sudo mkdir --parents /etc/nomad.d
sudo chmod 700 /etc/nomad.d

cat << "NOMAD" > /etc/nomad.d/nomad.hcl
datacenter = "dc1"
data_dir = "/scratch/local"
telemetry {
  collection_interval = "1s"
  disable_hostname = true
  prometheus_metrics = true
  publish_allocation_metrics = true
  publish_node_metrics = true
}
NOMAD

cat << "CLIENT" > /etc/nomad.d/client.hcl
client {
  enabled = true
}
CLIENT

sudo systemctl enable nomad
