#!/usr/bin/env bash
set -Eeuo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# todo: port to Makefile


if [ -z "${1-}" ]; then
  # todo: add some template to mktemp
  src_chroot=$(mktemp -d)
  new_chroot=true
else
  src_chroot="$1"
  new_chroot=false
fi


pkgs=(
#neovim

# -------------------------------------------------
# BELOW are packages I was installing in the prior version of this script.
# Keeping them here handy incase I need them again. I'd like to validate the
# need of each one.
#
# core system package. Without these system will not boot
#locales
#openssh-server # it will boot, but I like remote access
#initramfs-tools
#linux-generic

# debugging / util. These increase size, but are nice to have
#htop
#mosh
# vim-tiny

# application specific
# todo: should thier own scripts handle installing these?
#gettext-base    # needed for envsubst, in consul install
#keepalived      # used for poor mans load balanceer
#nfs-common      # for NFS share, used by traefik

# these need to be verified that they are required
#ca-certificates
#curl
#gpg-agent
#parted
#pixz
#rsync
#software-properties-common
#tar
#unzip
#xfsprogs
)

[[ $new_chroot == true ]] && "$DIR/bin/generate_chroot" "$src_chroot" "${pkgs[@]}"
echo "original chroot $src_chroot"

# even though the naive path would be to provison the chroot we just created,
# still copy it over incase we want to inspect the base chroot, or tweak
# something.

dist_chroot=$(mktemp -d)
"$DIR/bin/copy_chroot" "$src_chroot" "$dist_chroot"
echo "new chroot      $dist_chroot"

# these modules are installed in the order given in the array.
modules=(
  inital_prep
  initramfs_tools
  babashka
  docker
  keepalived
  nomad_agent
  traefik
  consul_agent
  glusterfs
  mounts
  scheduled_reboot
  final_prep
)

sudo cp "$DIR/modules/_common.bash" "$dist_chroot/tmp/"
for module in "${modules[@]}"; do
  if [[ -f "${DIR}/modules/$module/setup" ]]; then
    "${DIR}/modules/$module/setup" "$dist_chroot"
  fi

  if [[ -f "${DIR}/modules/$module/install" ]]; then
    "$DIR/bin/provision_chroot" "$dist_chroot" "${DIR}/modules/$module/install"
  fi
done

#PIXZ_COMPRESSION_LEVEL=${PIXZ_COMPRESSION_LEVEL:-9}
"$DIR/bin/package_chroot" "$dist_chroot"
