#!/usr/bin/env bash
set -Eeu

packages=(
#curl
#gettext-base    # needed for envsubst, in consul install
#glances         # system monitoring
#gpg-agent
#htop            # ligherwirght monitoring
#ifupdown
#keepalived
#linux-generic   # need firmware and goodies
#mosh            # better ssh
#neovim          # my favorite text editor
#nfs-common
#pixz            # need by ramroot script
#resolvconf      # dns
#rsync
#software-properties-common
#tar
#unzip
#xfsprogs
ca-certificates # HTTPS is important
locales         # sane working environment
openssh-server  # remote access
systemd         # init
systemd-sysv    # /sbin/init symlink
udev            # system devices
vim             # light text editing
)
apt-get update -qq

# without this, resolvconf will failed to install and break the build
echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
apt-get install -qy  "${packages[@]}"
apt-get clean all

locale-gen 'en_US.UTF-8'
update-locale LANG=en_US.UTF-8

sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/'     /etc/ssh/sshd_config

mkdir -p /root/.ssh
cat << SSH >> /root/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZq6q45h3OVj7Gs4afJKL7mSz/bG+KMG0wIOEH+wXmzDdJ0OX6DLeN7pua5RAB+YFbs7ljbc8AFu3lAzitQ2FNToJC1hnbLKU0PyoYNQpTukXqP1ptUQf5EsbTFmltBwwcR1Bb/nBjAIAgi+Z54hNFZiaTNFmSTmErZe35bikqS314Ej60xw2/5YSsTdqLOTKcPbOxj2kulznM0K/z/EDcTzGqc0Mcnf51NtzxlmB9NR4ppYLoi7x+rVWq04MbdAmZK70p5ndRobqYSWSKq+WDUAt2+CiTm6ItDowTLuo3zjHyYV1eCnB35DdakKVldIHrQyhmhbf5hJi6Ywx6XCzlFoNpkl/++RrJT2rf0XpGdlRoLQoKFvNRfnO4LI499SIfFb9Pwq7LhF1C1kTmshN/9S44d6VCCYXLE4uS8OPv7IXxUvFQZaIKCbomd2FzXxUwf4lg2gSlczysgDaVsMAUvlfDVgTFX8Xt1LFl3DqNtUiUpa9+Jnst/jCqqOBf3e8= kyle@alpha
SSH
