#!/usr/bin/env bash
set -Eeu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

packages=(
  parted # for formatting the disks
)

apt update -qq
apt-get install -qy  "${packages[@]}"
apt-get clean all

cp "$DIR/format-scratch.service"  "/etc/systemd/system/"
cp "$DIR/scratch-local.mount"     "/etc/systemd/system/"
#cp "$DIR/mnt-nfs.mount"           "/etc/systemd/system/"

systemctl enable format-scratch
systemctl enable scratch-local.mount
#systemctl enable mnt-nfs.mount
