#!/usr/bin/env bash
set -Eeu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "/tmp/_common.bash"
common.install_packages parted

cp "$DIR/"*.service  "/etc/systemd/system/"
cp "$DIR/"*.mount    "/etc/systemd/system/"

# todo: probably need more explicit dependencies here
systemctl enable format-scratch.service
systemctl enable mnt-nfs.mount
#systemctl enable mnt-shared.mount
systemctl enable scratch-gluster.mount
systemctl enable scratch-local.mount
